# Generated by Django 5.1.4 on 2026-07-12 06:23

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("phone", models.CharField(blank=True, max_length=20)),
                (
                    "preferred_language",
                    models.CharField(
                        choices=[
                            ("en", "English"),
                            ("ru", "Russian"),
                            ("zh", "Chinese"),
                            ("ja", "Japanese"),
                            ("ko", "Korean"),
                            ("fr", "French"),
                            ("de", "German"),
                            ("th", "Thai"),
                        ],
                        default="en",
                        max_length=5,
                    ),
                ),
                (
                    "plan",
                    models.CharField(
                        choices=[
                            ("free", "Free"),
                            ("home", "Home"),
                            ("management", "Management"),
                            ("corporate", "Corporate"),
                        ],
                        default="free",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Worker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                (
                    "nickname",
                    models.CharField(blank=True, help_text="Thai nickname", max_length=50),
                ),
                ("phone", models.CharField(max_length=20)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("maid", "Maid / Housekeeper"),
                            ("nanny", "Nanny / Babysitter"),
                            ("driver", "Driver"),
                            ("cook", "Cook / Chef"),
                            ("gardener", "Gardener"),
                            ("guard", "Security Guard"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "salary",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Monthly salary in THB",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("start_date", models.DateField()),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "employer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workers",
                        to="workers.employer",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["employer", "is_active"], name="workers_wor_employe_3fa1ef_idx"
                    ),
                    models.Index(fields=["role"], name="workers_wor_role_0c1984_idx"),
                ],
            },
        ),
    ]
